# Generated by Django 2.1.5 on 2019-02-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligas',
            name='endate',
            field=models.DateTimeField(default='1000-02-03 19:57:26.000000'),
        ),
    ]
