# Generated by Django 2.1.5 on 2019-02-06 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0003_liga_lobby'),
    ]

    operations = [
        migrations.CreateModel(
            name='players_lobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=3)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.liga_lobby')),
                ('steamid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.steamuser')),
            ],
        ),
    ]
