# Generated by Django 2.1.5 on 2019-02-06 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0006_auto_20190206_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligas',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ligas',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ligas',
            name='desc',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='ligas',
            name='endate',
            field=models.DateTimeField(default='1000-02-03 19:57:26.000000'),
        ),
        migrations.AddField(
            model_name='ligas',
            name='nome',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='ligas',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ligas',
            name='slots',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ligas',
            name='slug',
            field=models.CharField(default=None, max_length=110),
        ),
    ]
