# Generated by Django 2.1.5 on 2019-02-06 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0008_remove_ligas_endate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligas',
            name='endate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
