# Generated by Django 2.1.5 on 2019-02-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0011_players_lobby_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players_lobby',
            name='slug',
        ),
        migrations.AddField(
            model_name='liga_lobby',
            name='lug',
            field=models.CharField(default=None, max_length=110),
        ),
    ]
