# Generated by Django 2.1.5 on 2019-02-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0016_liga_lobby_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='liga_lobby',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
    ]
