# Generated by Django 2.1.7 on 2019-02-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0017_liga_lobby_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamuser',
            name='banido',
            field=models.BooleanField(default=False),
        ),
    ]
