# Generated by Django 2.1.5 on 2019-02-04 20:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ligas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('slug', models.CharField(max_length=110)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('price', models.FloatField(default=0.0)),
                ('slots', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='players_liga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.BigIntegerField(default=1000)),
                ('active', models.BooleanField(default=True)),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.ligas')),
            ],
        ),
        migrations.CreateModel(
            name='steamuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steamid', models.CharField(max_length=200)),
                ('nome', models.CharField(max_length=100)),
                ('avatar', models.TextField()),
                ('avatarmedium', models.TextField()),
                ('avatarfull', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='players_liga',
            name='steamid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.steamuser'),
        ),
    ]
