# Generated by Django 2.1.5 on 2019-02-06 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_ligas_endate'),
    ]

    operations = [
        migrations.CreateModel(
            name='liga_lobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=11)),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.ligas')),
            ],
        ),
    ]
