# Generated by Django 2.1.5 on 2019-02-06 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0005_liga_lobby_slots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligas',
            name='active',
        ),
        migrations.RemoveField(
            model_name='ligas',
            name='date',
        ),
        migrations.RemoveField(
            model_name='ligas',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='ligas',
            name='endate',
        ),
        migrations.RemoveField(
            model_name='ligas',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='ligas',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ligas',
            name='slots',
        ),
        migrations.RemoveField(
            model_name='ligas',
            name='slug',
        ),
    ]
