# Generated by Django 2.1.5 on 2019-02-06 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0007_auto_20190206_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligas',
            name='endate',
        ),
    ]
