# Generated by Django 2.1.5 on 2019-02-08 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0014_auto_20190206_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='liga_lobby',
            name='lobbycriador',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='paginas.steamuser'),
        ),
    ]
