# Generated by Django 2.1.5 on 2019-02-09 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0015_liga_lobby_lobbycriador'),
    ]

    operations = [
        migrations.AddField(
            model_name='liga_lobby',
            name='bot',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
